import { useEffect, useState } from "react";
function AICommandcenter({
  criticalPatients,
  pendingApprovals,
  totalRevenue,
}) {

  const [aiDecision, setAiDecision] = useState(
  "Generating AI recommendation..."
);

useEffect(() => {

  const getDecision = async () => {

    try {

      const response = await fetch(
        "http://localhost:5000/api/ai/supervisor-decision",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            criticalPatients,
            pendingApprovals,
          }),
        }
      );

      const data = await response.json();

      if (data.success) {
        setAiDecision(
  data.decision.replace(/\*\*/g, "")
);
      }

    } catch (error) {
      console.log(error);
      setAiDecision("Unable to generate AI recommendation.");
    }

  };

  getDecision();

}, [criticalPatients, pendingApprovals]);

  return (
    <div className="bg-white border border-slate-200 rounded-3xl p-8 shadow-sm mb-8">

      <div className="flex items-center justify-between mb-6">

      <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
  🧠 AI Command Center
</h2>

        <span className="bg-emerald-100 text-emerald-700 px-4 py-2 rounded-full text-sm font-medium">
  🟢 Supervisor Agent Active
</span>

      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">

  <div className="bg-red-50 border border-red-100 rounded-2xl p-5">
    <p className="text-sm text-slate-500">Hospital Risk Level</p>
    <span
  className={`inline-flex px-4 py-2 rounded-full text-lg font-bold mt-2 ${
    criticalPatients > 5
      ? "bg-red-100 text-red-700"
      : "bg-green-100 text-green-700"
  }`}
>
  {criticalPatients > 5 ? "HIGH" : "NORMAL"}
</span>
  </div>

  <div className="bg-orange-50 border border-orange-100 rounded-2xl p-5">
    <p className="text-sm text-slate-500">Critical Cases</p>
    <h3 className="text-2xl font-bold text-orange-600">
      {criticalPatients}
    </h3>
  </div>

  <div className="bg-yellow-50 border border-yellow-100 rounded-2xl p-5">
    <p className="text-sm text-slate-500">Pending Approvals</p>
    <h3 className="text-2xl font-bold text-yellow-600">
      {pendingApprovals}
    </h3>
  </div>

    <div
  className={`rounded-2xl p-5 border
  ${
    criticalPatients > 10
      ? "bg-red-50 border-red-100"
      : criticalPatients > 5 || pendingApprovals > 3
      ? "bg-yellow-50 border-yellow-100"
      : "bg-green-50 border-green-100"
  }`}
>
  <p className="text-sm text-slate-500">
    Workflow Health
  </p>

  <h3
    className={`text-2xl font-bold
    ${
      criticalPatients > 10
        ? "text-red-600"
        : criticalPatients > 5 || pendingApprovals > 3
        ? "text-yellow-600"
        : "text-green-600"
    }`}
  >
    {criticalPatients > 10
      ? "Critical"
      : criticalPatients > 5 || pendingApprovals > 3
      ? "High Risk"
      : "Stable"}
  </h3>
</div>

</div>
<div className="mt-6 bg-slate-50 border border-slate-200 rounded-2xl p-5">

  <p className="text-sm font-semibold text-slate-500 mb-4 flex items-center gap-2">
  🤖 AI Supervisor Recommendation
</p>

<div className="bg-white rounded-xl border border-slate-200 p-4">
  <div className="text-slate-800 leading-8 whitespace-pre-line">

  {aiDecision
    .split("\n")
    .filter((line) => line.trim() !== "")
    .map((line, index) => {

      if (line.startsWith("Risk Level:")) {
        return (
          <p key={index} className="mb-3">
            <span className="font-bold text-red-600">
              🚨 Risk Level:
            </span>{" "}
            {line.replace("Risk Level:", "").trim()}
          </p>
        );
      }

      if (line.startsWith("Recommended Action:")) {
        return (
          <p key={index} className="mb-3">
            <span className="font-bold text-blue-600">
              📋 Recommended Action:
            </span>{" "}
            {line.replace("Recommended Action:", "").trim()}
          </p>
        );
      }

      if (line.startsWith("Explanation:")) {
        return (
          <p key={index}>
            <span className="font-bold text-emerald-600">
              💡 Explanation:
            </span>{" "}
            {line.replace("Explanation:", "").trim()}
          </p>
        );
      }

      return (
        <p key={index}>
          {line}
        </p>
      );

    })}

</div>

  <div className="mt-4 pt-3 border-t border-slate-200 text-xs text-slate-500 flex justify-between">
    <span>Generated by Supervisor Agent</span>
    <span>Just now</span>
  </div>
</div>

</div>
</div>

  );
}

export default AICommandcenter;